version: '2'
mpp-vars:
  name: mycontainer-manifest
  use_containers_extra_store: true
  use_composefs: true
  dracut_add_modules:
  - validator
  is_autoinit_supported: false

pipelines:
- name: rootfs
  build: name:build
  stages:

  # Install some RPMs
  - type: org.osbuild.rpm
    options:
      gpgkeys:
      - mpp-eval: distro_gpg_keys
      disable_dracut: true
      exclude:
        docs: true
    inputs:
      packages:
        type: org.osbuild.files
        origin: org.osbuild.source
        mpp-depsolve:
          architecture: $arch
          ignore-weak-deps: true
          module-platform-id: $distro_module_id
          baseurl: $distro_baseurl_repo
          repos:
            mpp-join:
            - mpp-eval: image_repos
            - mpp-eval: extra_repos
            - - id: copr_can_utils
                baseurl: https://download.copr.fedorainfracloud.org/results/@centos-automotive-sig/can-utils/centos-stream-9-$arch/
              - id: copr_validator
                baseurl: https://download.copr.fedorainfracloud.org/results/@centos-automotive-sig/validator/centos-stream+epel-next-9-$arch/
          packages:
            mpp-join:
            - mpp-eval: image_rpms
            - - vim
              - wget
              - podman
              - tar
              - validator
              - tree
              - less
              - openssh-clients
              - openssh-server
              - kernel-automotive-modules-extra
              # Required for the semanage command:
              - policycoreutils-python-utils

  # Get the CS9 base container in
  - type: org.osbuild.skopeo
    inputs:
      images:
        type: org.osbuild.containers
        origin: org.osbuild.source
        mpp-resolve-images:
          images:
            - source: quay.io/centos/centos
              tag: stream9
              name: localhost/cs9
    options:
      destination:
        type: containers-storage
        storage-path:
          mpp-eval: containers_extra_store

  # Install the files we want on the image
  - type: org.osbuild.copy
    inputs:
      # Get a V1 quadlet
      inlinefile1:
        type: org.osbuild.files
        origin: org.osbuild.source
        mpp-embed:
          id: app_v1.container
          path: ./files/app_v1.container
      # Install the public key used by validator
      inlinefile2:
        type: org.osbuild.files
        origin: org.osbuild.source
        mpp-embed:
          id: public.pem
          path: ./files/public.pem
      # Install the validator-boot configuration file
      inlinefile3:
        type: org.osbuild.files
        origin: org.osbuild.source
        mpp-embed:
          id: validator-boot.conf
          path: ./files/validator-boot.conf
      # Install the validator configuration file
      inlinefile4:
        type: org.osbuild.files
        origin: org.osbuild.source
        mpp-embed:
          id: validator.conf
          path: ./files/validator.conf
      # Install the dracut module for validator
      inlinefile6:
        type: org.osbuild.files
        origin: org.osbuild.source
        mpp-embed:
          id: validator-boot.service
          path: ./files/validator-boot.service
    options:
      paths:
      - from:
          mpp-format-string: input://inlinefile1/{embedded['app_v1.container']}
        to: tree:///usr/share/containers/systemd/app_v1.container
      - from:
          mpp-format-string: input://inlinefile2/{embedded['public.pem']}
        to: tree:///usr/lib/validator/keys/etc.key
      - from:
          mpp-format-string: input://inlinefile3/{embedded['validator-boot.conf']}
        to: tree:///etc/validator/boot.d/validator-boot.conf
      - from:
          mpp-format-string: input://inlinefile4/{embedded['validator.conf']}
        to: tree:///etc/validator/validator.conf
      - from:
          mpp-format-string: input://inlinefile5/{embedded['install_app']}
        to: tree:///usr/bin/install_app
      - from:
          mpp-format-string: input://inlinefile6/{embedded['validator-boot.service']}
        to: tree:///usr/lib/dracut/modules.d/98validator/validator-boot.service

  # Delete the /etc/container/systemd folder so we can symlink it instead
  - type: org.osbuild.lorax-script
    options:
      path: auto/remove
      product:
        name: /etc/containers/systemd

  # Create the guest user
  - type: org.osbuild.users
    options:
      users:
        guest:
          password: "$6$xoLqEUz0cGGJRx01$H3H/bFm0myJPULNMtbSsOFd/2BnHqHkMD92Sfxd.EKM9hXTWSmELG8cf205l6dktomuTcgKGGtGDgtvHVXSWU."
          gid: 999
          uid: 999
